version: '3.8'
services:
  postgres:
    container_name: container-pg
    image: postgres
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    build:
      dockerfile: ./docker/migration/Dockerfile
      context: .
    environment:
      - DATABASE_USERNAME=user
      - DATABASE_PASSWORD=password
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=db
    depends_on:
      postgres:
        condition:
          service_healthy

volumes:
  db:
    driver: local
  postgres-data:
    driver: local
